apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::637423626987:role/eksctl-simple-jwt-api-nodegroup-ng-NodeInstanceRole-HAdyco0uRXi7
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::637423626987:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2024-03-12T03:21:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1245"
  uid: 20dde97e-ac4a-4408-9d2d-9e3217caa4a2
